pipeline {
  agent any
  tools {
    maven 'mvn'
    jdk 'JDK 8'
  }
  stages {
    stage('Preparation') {
      steps{
        deleteDir()
        sh 'git clone git@github.com:opengeospatial/teamengine.git .'
      }
    }
    stage('Test') {
      steps{
        sh 'mvn --version'
        sh 'cd teamengine-tests && mvn clean com.smartbear.soapui:soapui-maven-plugin:test -Dsoapui.test.fail.ignore=true -Dsoapui.teamengine.endpoint=${teamengineEndpoint} -Dsoapui.teamengine.user=${teamengineUser} -Dsoapui.teamengine.password=${teamenginePassword} -Dsoapui.testng.ets.code=${testngEtsCode} -Dsoapui.testng.iut=${testngIut} -Dsoapui.ctl.ets.code=${ctlEtsCode} -Dsoapui.ctl.iut=${ctlIut}'
      }
    }
    stage('Results') {
      steps{
        junit '**/target/soapui/TEST-*.xml'
        archive 'target/*'
      }
    }
  }
}
